//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QPDFEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QPDFEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap annotation_16 {
            get {
                object obj = ResourceManager.GetObject("annotation_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap annotation_20 {
            get {
                object obj = ResourceManager.GetObject("annotation_20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap annotation_24 {
            get {
                object obj = ResourceManager.GetObject("annotation_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] app_icon {
            get {
                object obj = ResourceManager.GetObject("app_icon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap app_icon_256 {
            get {
                object obj = ResourceManager.GetObject("app_icon_256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap area_delete_16 {
            get {
                object obj = ResourceManager.GetObject("area_delete_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap area_delete_20 {
            get {
                object obj = ResourceManager.GetObject("area_delete_20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap area_delete_24 {
            get {
                object obj = ResourceManager.GetObject("area_delete_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap EDS_Logo {
            get {
                object obj = ResourceManager.GetObject("EDS_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   ✕과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Find_Close {
            get {
                return ResourceManager.GetString("Find_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모두 찾기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Find_FindAll {
            get {
                return ResourceManager.GetString("Find_FindAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   찾기:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Find_LabelFind {
            get {
                return ResourceManager.GetString("Find_LabelFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   바꾸기:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Find_LabelReplace {
            get {
                return ResourceManager.GetString("Find_LabelReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   대소문자 구분과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Find_MatchCase {
            get {
                return ResourceManager.GetString("Find_MatchCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모두 바꾸기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Find_ReplaceAll {
            get {
                return ResourceManager.GetString("Find_ReplaceAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   정보(&amp;A)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   편집(&amp;E)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuEdit {
            get {
                return ResourceManager.GetString("MenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   종료(&amp;X)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파일(&amp;F)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   찾기 / 바꾸기(&amp;H)  Ctrl+H과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuFindReplace {
            get {
                return ResourceManager.GetString("MenuFindReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   도움말(&amp;?)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사용 방법(&amp;H)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuHowToUse {
            get {
                return ResourceManager.GetString("MenuHowToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   열기(&amp;O)  Ctrl+O과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuOpen {
            get {
                return ResourceManager.GetString("MenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모든 변경 사항 되돌리기(&amp;Z)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuRevertAll {
            get {
                return ResourceManager.GetString("MenuRevertAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저장(&amp;S)  Ctrl+S과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuSave {
            get {
                return ResourceManager.GetString("MenuSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다른 이름으로 저장(&amp;A)  Ctrl+Shift+S과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuSaveAs {
            get {
                return ResourceManager.GetString("MenuSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   보기(&amp;V)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MenuView {
            get {
                return ResourceManager.GetString("MenuView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PDF 파일을 열어주세요. 파란 영역을 클릭하면 텍스트를 수정할 수 있습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Status_Default {
            get {
                return ResourceManager.GetString("Status_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap text_16 {
            get {
                object obj = ResourceManager.GetObject("text_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap text_20 {
            get {
                object obj = ResourceManager.GetObject("text_20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap text_24 {
            get {
                object obj = ResourceManager.GetObject("text_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   🔍 찾기/바꾸기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ToolbarFind {
            get {
                return ResourceManager.GetString("ToolbarFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ▶과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ToolbarNext {
            get {
                return ResourceManager.GetString("ToolbarNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   📂 열기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ToolbarOpen {
            get {
                return ResourceManager.GetString("ToolbarOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   – / –과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ToolbarPageLabelDefault {
            get {
                return ResourceManager.GetString("ToolbarPageLabelDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ◀과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ToolbarPrev {
            get {
                return ResourceManager.GetString("ToolbarPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ↺ 되돌리기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ToolbarRevert {
            get {
                return ResourceManager.GetString("ToolbarRevert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   💾 저장과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ToolbarSave {
            get {
                return ResourceManager.GetString("ToolbarSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   📋 다른 이름으로과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ToolbarSaveAs {
            get {
                return ResourceManager.GetString("ToolbarSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   확대: 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ToolbarZoomLabel {
            get {
                return ResourceManager.GetString("ToolbarZoomLabel", resourceCulture);
            }
        }
    }
}
